// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcjdxuzgkfjztlivqhtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjamR4dXpna2ZqenRsaXZxaHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTE2MjYsImV4cCI6MjA2MTIyNzYyNn0.ul3QQU89aurjB50-ziIXHr1hpwyd4PyXtJefSCx_VuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);